### ISSUE TITLE
Rootston

### ISSUE THREAD

**Issue by Timidger** [swaywm/wlroots-rs#22]
To fully test the library, we should recreate [wlroot's rootston](https://github.com/swaywm/wlroots/tree/master/rootston) in **100% safe** Rust.

Once this is done, and wlroots has stabilized (and started actually releasing versions), work will begin on porting [Way Cooler](https://github.com/way-cooler/way-cooler)

# Prerequisites 
Here are the prereqs needed to get rootston up to spec. There are links to relevant issues for each wlroots type where we outline how we will wrap them to ensure safety.

* Make basic examples first
  - [X] Minimal
  - [X] Simple
  - [X] Pointer
  - [X] [Touch](https://github.com/swaywm/wlroots-rs/issues/21)
  - [ ] [Tablet](https://github.com/swaywm/wlroots-rs/issues/20)
  - [ ] [Output Layout](https://github.com/swaywm/wlroots-rs/issues/19)
  - [ ] [Multi-pointer](https://github.com/swaywm/wlroots-rs/issues/18)
  - [X] [Rotation](https://github.com/swaywm/wlroots-rs/issues/17)
* Types
  - Shells (possibly try to unify these?)
    - [X] [wlr_wl_shell](https://github.com/swaywm/wlroots-rs/issues/23)
    - [X] [wlr_xdg_shell_v6](https://github.com/swaywm/wlroots-rs/issues/24)
    - [ ] [wlr_xdg_shell](#95)
  - Input
    - [X] [wlr_seat](https://github.com/swaywm/wlroots-rs/issues/37)
    - [ ] [wlr_seat_client](https://github.com/swaywm/wlroots-rs/issues/32)
    - [X] [wlr_cursor](https://github.com/swaywm/wlroots-rs/issues/33)
    - [X] [wlr_xcursor](https://github.com/swaywm/wlroots-rs/issues/34)
    - [X] [wlr_xcursor_theme](https://github.com/swaywm/wlroots-rs/issues/35)
    - [ ] [wlr_data_device](https://github.com/swaywm/wlroots-rs/issues/31)
    - [ ] [wlr_input_device](https://github.com/swaywm/wlroots-rs/issues/30) (is a union for the following):
      - [X] [wlr_keyboard](https://github.com/swaywm/wlroots-rs/issues/25)
      - [X] [wlr_pointer](https://github.com/swaywm/wlroots-rs/issues/26)
      - [X] [wlr_touch](https://github.com/swaywm/wlroots-rs/issues/27)
      - [ ] [wlr_tablet_pad](https://github.com/swaywm/wlroots-rs/issues/28)
      - [ ] [wlr_tablet_tool](https://github.com/swaywm/wlroots-rs/issues/29)
  - Output
    - [X] [wlr_output](https://github.com/swaywm/wlroots-rs/issues/38)
    - [X] [wlr_output_mode](https://github.com/swaywm/wlroots-rs/issues/39)
    - [X] [wlr_output_cursor](https://github.com/swaywm/wlroots-rs/issues/41)
    - [X] [wlr_output_layout](https://github.com/swaywm/wlroots-rs/issues/42)
    - [X] [wlr_output_layout_output](https://github.com/swaywm/wlroots-rs/issues/43)
  - Misc
    - [X] [wlr_box](https://github.com/swaywm/wlroots-rs/issues/44) ("Area")
    - [X] [wlr_list](https://github.com/swaywm/wlroots-rs/issues/45)
    - [ ] [wlr_region](https://github.com/swaywm/wlroots-rs/issues/46)
* Functionality wrapped
  - [X] logging
  - [ ] rendering (still in flux, holding off)
  - [ ] [Extensions](https://github.com/swaywm/wlroots-rs/issues/10)

# Rootston
* Configuration
  - [X] Ini parsing
  - [ ] Xwayland configurable
  - [ ] Output layout
  - [ ] Cursor-output mapping
  - [ ] Per-device configuration for input
  - Keybinding
    - [ ] Meta key
    - Commands
      - [ ] exit
      - [ ] exec
      - [ ] close
      - [ ] next_window
